/*
 * Golden grid-raster contract: buildGridImageData vs render_map_png, per cell.
 *
 * WHY THIS EXISTS
 * ---------------
 * The Python suite never runs this JS and this suite never runs Python, so a
 * divergence between the two renderers passes both green while the map visibly
 * differs in a browser. renderer.test.mjs already checks 256 random cells against
 * a *label*; this checks **RGBA per cell across six real maps**, including the two
 * registration details a flat random grid cannot reach: the room mask's
 * _ro_dx/_ro_dy offset, and both room_id_offset regimes (legacy 1, novel 0).
 *
 * WHAT IT CAN AND CANNOT PROVE
 * ----------------------------
 * `buildGridImageData` is PURE — it returns the exact Uint8ClampedArray the browser
 * would `putImageData` — so jsdom's missing canvas is not a blocker for the grid
 * layer. It IS a blocker for everything else: the comparison is at SOURCE-GRID
 * RESOLUTION, one texel per cell, BEFORE the Y-flip and before the NEAREST resize
 * to `max_px`. Both of those are exact and parameter-free given the raster (the
 * client does them as one negative-scale setTransform with imageSmoothingEnabled
 * off), so an equal raster means an equal grid layer — but the dock, trail, robot,
 * zones and room labels are drawn at output resolution by both ends and are NOT
 * covered here. This is not a full-frame image diff and must not be called one.
 *
 * THE TWO PALETTES DELIBERATELY DIFFER, AND THIS ASSERTS WHICH
 * -----------------------------------------------------------
 *   wall / free floor / cleaned floor  ->  EXACT RGB equality (light theme).
 *   unknown / void                     ->  server (30,30,30) opaque vs client fully
 *                                          transparent, on purpose: the card's own
 *                                          background shows through the void.
 *   room fills                         ->  different palettes on purpose. The server
 *                                          cycles 8 hues (_ROOM_PALETTE reserves
 *                                          index 0); the client uses Paul Tol's
 *                                          10-hue colour-blind-safe "muted" scheme.
 *                                          So room colour is checked STRUCTURALLY:
 *                                          the same cells must be room-filled, and
 *                                          each room id must take exactly one hue.
 *
 * The fixture is generated by tests/generate_golden_fixture.py, and
 * tests/test_golden_fixture.py fails if it goes stale AND if its "expected" colours
 * stop matching a real render_map_png call. The two halves cannot drift silently.
 *
 * FALSIFIABILITY: set EUFY_RENDERER_SRC to a deliberately broken copy of
 * eufy-map-renderer.js to watch this suite fail, without editing the shipped file.
 */
import fs from "node:fs";
import zlib from "node:zlib";

const SRC = process.env.EUFY_RENDERER_SRC
  ? new URL("file://" + process.env.EUFY_RENDERER_SRC)
  : new URL("../../custom_components/robovac_mqtt/frontend/eufy-map-renderer.js", import.meta.url);
const code = fs.readFileSync(SRC, "utf8");
// The module lives outside any package.json, so node would treat its .js as CJS and
// reject `export`. A data: URL evaluates it as a real ES module — which is also how
// the browser loads it. It has no imports of its own, so nothing needs resolving.
const mod = await import("data:text/javascript;base64," + Buffer.from(code, "utf8").toString("base64"));
const { decodeGeometry, buildGridImageData, ROOM_PALETTE, DEFAULT_PALETTE } = mod;

let fail = 0;
const ok = (c, m) => { if (c) console.log("  ok:", m); else { console.error("  FAIL:", m); fail++; } };

const fixture = JSON.parse(
  fs.readFileSync(new URL("./fixtures/golden_render.json", import.meta.url), "utf8"),
);
const inflate = (b64) => new Uint8Array(zlib.inflateSync(Buffer.from(b64, "base64")));
const CLASS_BASE = fixture.room_class_base;
const rgbaKey = (a) => `${a[0]},${a[1]},${a[2]},${a[3]}`;
const same = (a, b) => a[0] === b[0] && a[1] === b[1] && a[2] === b[2] && a[3] === b[3];
// A palette entry may be [r,g,b] or [r,g,b,a]; the raster always writes four bytes.
const rgba = (c) => [c[0], c[1], c[2], c.length > 3 ? c[3] : 255];

// ---- 1. palette agreement, stated rather than assumed -----------------------
// The fixture carries _PIXEL_COLORS and _ROOM_PALETTE straight from map_stream.py
// (imported there, never retyped), so this compares the two ends' real tables.
console.log("[1] palette agreement between _PIXEL_COLORS and DEFAULT_PALETTE");
{
  const server = fixture.server_pixel_colors;
  const eq = (a, b) => a[0] === b[0] && a[1] === b[1] && a[2] === b[2];
  ok(eq(DEFAULT_PALETTE.wall.light, server["1"]),
    `wall matches exactly: client [${DEFAULT_PALETTE.wall.light}] vs server [${server["1"]}]`);
  ok(eq(DEFAULT_PALETTE.floor.light, server["2"]),
    `free floor matches exactly: client [${DEFAULT_PALETTE.floor.light}] vs server [${server["2"]}]`);
  ok(eq(DEFAULT_PALETTE.cleaned.light, server["3"]),
    `cleaned floor matches exactly: client [${DEFAULT_PALETTE.cleaned.light}] vs server [${server["3"]}]`);

  // The one non-room deliberate divergence. Asserted as a fact, not skipped: if the
  // void ever stops being transparent, the reason it was is in the comment above.
  ok(DEFAULT_PALETTE.unknown[3] === 0,
    `void is transparent on the client by design (server paints it [${server["0"]}])`);

  // Room hues. These are NOT expected to match, and the room checks below are
  // structural for exactly that reason. The conditional is the part that matters:
  // if someone ever aligns the hue tables, the index arithmetic has to be aligned
  // in the same commit or the maps still differ — server slot is
  // `1 + (stored - 1) % 8` into a 9-entry table, client slot is `(stored - 1) % 10`
  // into a 10-entry one, so even identical hue lists would disagree from room 9 on.
  const serverRooms = fixture.server_room_palette;
  const identical =
    serverRooms.length === ROOM_PALETTE.length &&
    serverRooms.every((c, i) => eq(c, ROOM_PALETTE[i]));
  console.log(
    `  note: room palettes differ by design — server ${serverRooms.length} entries ` +
    `(index 0 reserved, ${serverRooms.length - 1} cycling), client ${ROOM_PALETTE.length} ` +
    `(Paul Tol muted, none reserved). Room fills are checked structurally.`,
  );
  ok(!identical, "room palettes are the two independent tables this suite assumes");
}

// ---- 1b. the client's own room hues, checked against their source comments ---
// Nothing cross-language can catch a *reordered* client palette: the server's hues
// are different by design, so there is no ground truth to compare against, and
// deriving the expectation from ROOM_PALETTE (as the room checks below must) is
// tautological in the hue values. What IS checkable is the renderer's own stated
// intent — every entry is documented with its hex — so the numbers are verified
// against the comments beside them rather than against a hand-copied second list.
// Swapping two entries' values then shows up here instead of passing silently.
console.log("[1b] ROOM_PALETTE entries match the hexes documented beside them");
{
  const block = code.slice(
    code.indexOf("export const ROOM_PALETTE = ["),
    code.indexOf("];", code.indexOf("export const ROOM_PALETTE = [")),
  );
  const found = [...block.matchAll(/\[\s*(\d+),\s*(\d+),\s*(\d+)\s*\]\s*,\s*\/\/\s*#([0-9A-Fa-f]{6})/g)];
  ok(found.length === ROOM_PALETTE.length,
    `all ${ROOM_PALETTE.length} entries carry a #hex comment (found ${found.length}) — ` +
    `if you drop one, this check silently weakens, so keep them`);
  let wrong = 0;
  found.forEach((m, i) => {
    const hex = m[4].toLowerCase();
    const want = [1, 3, 5].map((k) => parseInt(hex.slice(k - 1, k + 1), 16));
    const got = [Number(m[1]), Number(m[2]), Number(m[3])];
    if (got.join() !== want.join()) {
      wrong++;
      console.error(`  FAIL: ROOM_PALETTE[${i}] is [${got}] but its comment says #${hex} = [${want}]`);
    }
  });
  ok(wrong === 0, "no room hue drifted from the hex it is documented as");
  // Stated invariant in the renderer: Tol's #DDDDDD is his "BAD DATA" grey and is
  // deliberately not a room colour here — the void is what reads as absent data.
  ok(!ROOM_PALETTE.some((c) => c[0] === 221 && c[1] === 221 && c[2] === 221),
    "Tol's #DDDDDD bad-data grey is not used as a room hue");
}

// ---- 2. per-cell golden raster ----------------------------------------------
console.log("[2] every cell of every fixture map");
let totalCells = 0;
for (const c of fixture.cases) {
  const state = await decodeGeometry(c.payload);
  const expectedRgb = inflate(c.expected_rgb);
  const expectedClass = inflate(c.expected_class);
  const cells = c.cells;
  totalCells += cells;

  ok(expectedClass.length === cells && expectedRgb.length === cells * 3,
    `${c.name}: fixture describes all ${cells} cells`);

  for (const isDark of [false, true]) {
    const img = buildGridImageData(state, DEFAULT_PALETTE, isDark);
    const wall = rgba(isDark ? DEFAULT_PALETTE.wall.dark : DEFAULT_PALETTE.wall.light);
    const floor = rgba(isDark ? DEFAULT_PALETTE.floor.dark : DEFAULT_PALETTE.floor.light);
    const cleaned = rgba(isDark ? DEFAULT_PALETTE.cleaned.dark : DEFAULT_PALETTE.cleaned.light);
    const unknown = rgba(DEFAULT_PALETTE.unknown);

    const problems = [];
    // roomId -> client colour key, and colour key -> the room ids wearing it.
    const hueOfRoom = new Map();
    const roomsOfHue = new Map();
    const storedOfRoom = new Map();
    let roomCells = 0;

    for (let i = 0; i < cells; i++) {
      const o = i * 4;
      const got = [img.data[o], img.data[o + 1], img.data[o + 2], img.data[o + 3]];
      const cls = expectedClass[i];
      const serverRgb = [expectedRgb[i * 3], expectedRgb[i * 3 + 1], expectedRgb[i * 3 + 2]];
      const cell = state.occupancy[i] || 0;
      const pv = cell & 3;
      const subType = (cell >> 2) & 3;
      const stored = state.rooms_grid[i] || 0;
      const where = () => {
        const row = Math.floor(i / state.width);
        const col = i - row * state.width;
        return `${c.name}[${isDark ? "dark" : "light"}] cell ${i} (col ${col}, row ${row}, ` +
               `sub_type ${subType}, pv ${pv}, rooms_grid ${stored})`;
      };

      if (cls >= CLASS_BASE) {
        // --- room-filled on the server: the client must room-fill it too ---
        const roomId = cls - CLASS_BASE;
        roomCells++;
        if (!(stored > 0)) {
          problems.push(`${where()}: server filled room ${roomId} but rooms_grid is 0`);
          continue;
        }
        const want = rgba(ROOM_PALETTE[(stored - 1) % ROOM_PALETTE.length]);
        if (!same(got, want)) {
          problems.push(
            `${where()}: server room ${roomId} -> [${serverRgb}]; client should take ` +
            `hue ${(stored - 1) % ROOM_PALETTE.length} = [${want}] but drew [${got}]`,
          );
          continue;
        }
        const key = rgbaKey(got);
        const prev = hueOfRoom.get(roomId);
        if (prev !== undefined && prev !== key) {
          problems.push(`${where()}: room ${roomId} drawn as ${key} here and ${prev} elsewhere`);
        }
        hueOfRoom.set(roomId, key);
        storedOfRoom.set(roomId, stored);
        if (!roomsOfHue.has(key)) roomsOfHue.set(key, new Set());
        roomsOfHue.get(key).add(roomId);
      } else if (cls === 0) {
        // --- void: the one non-room place the palettes part company on purpose ---
        if (!same(got, unknown)) {
          problems.push(`${where()}: void must be the client's transparent [${unknown}], got [${got}]`);
        }
      } else {
        // --- wall / floor / cleaned: hard cross-language RGB equality ---
        const want = cls === 1 ? wall : cls === 2 ? floor : cleaned;
        if (!same(got, want)) {
          problems.push(`${where()}: expected class ${cls} colour [${want}], got [${got}]`);
        } else if (!isDark && (got[0] !== serverRgb[0] || got[1] !== serverRgb[1] || got[2] !== serverRgb[2] || got[3] !== 255)) {
          problems.push(
            `${where()}: server render_map_png says [${serverRgb}], client says [${got}]`,
          );
        }
      }
    }

    // A colour shared by two rooms is only legitimate when the client's own index
    // arithmetic collides them — the palette has 10 hues, so rooms 10 apart really
    // do share one. Anything else means two rooms were merged.
    for (const [key, ids] of roomsOfHue) {
      if (ids.size < 2) continue;
      const slots = new Set([...ids].map((id) => (storedOfRoom.get(id) - 1) % ROOM_PALETTE.length));
      if (slots.size !== 1) {
        problems.push(
          `${c.name}[${isDark ? "dark" : "light"}]: rooms ${[...ids].join(", ")} all drawn ${key} ` +
          `but their palette slots are ${[...slots].join(", ")}`,
        );
      }
    }

    const label =
      `${c.name} [${isDark ? "dark" : "light"}]: ${cells} cells, ${roomCells} room-filled`;
    ok(problems.length === 0,
      problems.length === 0
        ? label
        : `${label} — ${problems.length} mismatch(es); first 3:\n      ${problems.slice(0, 3).join("\n      ")}`);
  }
}

// ---- 2b. the latent one-slot shift between the two hue sequences ------------
// Harmless today because the palettes differ anyway, but it is a real asymmetry and
// it must not be discovered the day someone unifies them: the SERVER colours a room
// by the mask's STORED id (`_ROOM_PALETTE[1 + (stored_mask - 1) % 8]`), while the
// CLIENT colours it by `real_id + 1` (`ROOM_PALETTE[(wire - 1) % 10]`). Those are the
// same number only when room_id_offset == 1. On a novel device (offset 0) the client
// is one slot further along than the server for every room. Pinned here so the
// relationship is a checked fact rather than folklore.
console.log("[2b] room -> hue slot: client is (1 - room_id_offset) slots ahead of the server");
{
  const serverCycle = fixture.server_room_palette.length - 1; // index 0 is reserved
  for (const c of fixture.cases) {
    const state = await decodeGeometry(c.payload);
    const cls = inflate(c.expected_class);
    const wireOf = new Map();
    for (let i = 0; i < c.cells; i++) {
      if (cls[i] >= CLASS_BASE && !wireOf.has(cls[i] - CLASS_BASE)) {
        wireOf.set(cls[i] - CLASS_BASE, state.rooms_grid[i]);
      }
    }
    if (!wireOf.size) continue;
    const expectShift = 1 - c.room_id_offset;
    const wrong = [];
    for (const [real, wire] of wireOf) {
      if (real >= Math.min(serverCycle, ROOM_PALETTE.length)) continue; // past a wrap
      const clientSlot = (wire - 1) % ROOM_PALETTE.length;
      const serverSlot = (real + c.room_id_offset - 1) % serverCycle;
      if (clientSlot - serverSlot !== expectShift) {
        wrong.push(`room ${real}: client slot ${clientSlot}, server cycling slot ${serverSlot}`);
      }
    }
    ok(wrong.length === 0,
      `${c.name} (offset ${c.room_id_offset}): shift is ${expectShift} for all ` +
      `${wireOf.size} rooms${wrong.length ? " — " + wrong.slice(0, 3).join("; ") : ""}`);
  }
}

// ---- 3. coverage of the fixture itself --------------------------------------
// A golden test that quietly stopped covering the interesting cases is worse than
// none, because it still reports green.
console.log("[3] the fixture still covers what it claims to");
{
  const names = fixture.cases.map((c) => c.name);
  for (const need of ["apartment", "mask_origin_offset", "novel_offset0",
                      "all_combinations", "palette_cycle", "no_room_mask"]) {
    ok(names.includes(need), `case present: ${need}`);
  }
  const apartment = fixture.cases.find((c) => c.name === "apartment");
  ok(apartment.cells === 150 * 215, `apartment is the measured 150x215 = ${150 * 215} cells`);
  ok(apartment.payload.rooms.length >= 6, `apartment has ${apartment.payload.rooms.length} rooms`);
  // Legacy room id 0 is a real room (the T2266's Hallway) and is never truthiness-tested.
  ok(apartment.payload.rooms.some((r) => r.id === 0), "a real room with id 0 is present");
  ok(fixture.cases.find((c) => c.name === "novel_offset0").room_id_offset === 0,
    "the novel case really uses room_id_offset 0");
  console.log(`  note: ${totalCells} cells compared per theme, ${totalCells * 2} in total`);
}

console.log(fail === 0 ? "\nALL PASSED" : `\n${fail} FAILURES`);
process.exit(fail === 0 ? 0 : 1);
